name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 4321
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            sudo git pull
            sudo composer install
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan migrate:fresh --seed --force
